{{- if and .Values.api.enabled (or (not .Values.api.database.existingSecret) .Values.api.jwtSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf.api.fullname" . }}
  labels:
    {{- include "ccf.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.api.database.existingSecret }}
  CCF_DB_CONNECTION: {{ include "ccf.db.connection" . | quote }}
  {{- end }}
  {{- if .Values.api.jwtSecret }}
  CCF_JWT_SECRET: {{ .Values.api.jwtSecret | quote }}
  {{- end }}
{{- end }}
