{{- if and .Values.api.enabled .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ccf.api.fullname" . }}
  labels:
    {{- include "ccf.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  {{- if .Values.api.pdb.minAvailable }}
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  {{- else if .Values.api.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.api.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ccf.selectorLabels" (dict "ctx" . "component" "api") | nindent 6 }}
{{- end }}
{{- if and .Values.ui.enabled .Values.ui.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ccf.ui.fullname" . }}
  labels:
    {{- include "ccf.componentLabels" (dict "ctx" . "component" "ui") | nindent 4 }}
spec:
  {{- if .Values.ui.pdb.minAvailable }}
  minAvailable: {{ .Values.ui.pdb.minAvailable }}
  {{- else if .Values.ui.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.ui.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ccf.selectorLabels" (dict "ctx" . "component" "ui") | nindent 6 }}
{{- end }}
