{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ccf.postgres.fullname" . }}
  labels:
    {{- include "ccf.componentLabels" (dict "ctx" . "component" "postgres") | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "ccf.selectorLabels" (dict "ctx" . "component" "postgres") | nindent 4 }}
{{- end }}
