apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ccf-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ccf
  source:
    repoURL: https://github.com/erasmo-dominguez-stuff/2026.git
    # CHANGE-ME: branch/tag to track.
    targetRevision: main
    path: ccf/charts/ccf-app
    helm:
      releaseName: ccf-app
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ccf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
