apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ccf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Continuous Compliance Framework
  sourceRepos:
    - https://github.com/erasmo-dominguez-stuff/2026.git
    - https://grafana.github.io/helm-charts
  destinations:
    - namespace: ccf
      server: https://kubernetes.default.svc
    - namespace: observability
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
